#Prefix to all images
export COMPOSITION_NAME="qmcp"
#Path to persistent data
export DATA_PATH="./data"

#Add path to directory here in format:
#["{service_name}"]= "elements separated by whitespace"
#Directory tree in DATA_PATH would be like this:
#{DATA_PATH}/{service_name}/path/to/directory/or/file
declare -xA DATA_DIRS=(
    ["grafana"]="/etc/grafana /var/lib/grafana /usr/share/grafana /var/log/grafana"
    ["prometheus"]="/etc/prometheus /prometheus"
    ["nginx"]="/usr/share/nginx/html /etc/nginx"
    ["postgres"]="/var/lib/postgresql/data"
)
#["service_name"]= "source of docker image from {image} section in docker-compose"
#This option will override ones in docker-compose.yml
declare -xA DOCKER_IMAGES=(
    ["grafana"]="grafana/grafana-enterprise"
    ["prometheus"]="prom/prometheus"
    ["nginx"]="nginx"
    ["postgres"]="postgres"
    ["nginx-exporter"]="nginx/nginx-prometheus-exporter"
    ["postgres-exporter"]="quay.io/prometheuscommunity/postgres-exporter"
)
